/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import com.rivetlogic.portlet.service.persistence.CompletedPK;

import java.io.Serializable;

/**
 * The base model interface for the Completed service. Represents a row in the &quot;rivetlogic_ann_Completed&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rivetlogic.portlet.model.impl.CompletedModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rivetlogic.portlet.model.impl.CompletedImpl}.
 * </p>
 *
 * @author charles.rodriguez
 * @see Completed
 * @see com.rivetlogic.portlet.model.impl.CompletedImpl
 * @see com.rivetlogic.portlet.model.impl.CompletedModelImpl
 * @generated
 */
public interface CompletedModel extends BaseModel<Completed> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a completed model instance should use the {@link Completed} interface instead.
	 */

	/**
	 * Returns the primary key of this completed.
	 *
	 * @return the primary key of this completed
	 */
	public CompletedPK getPrimaryKey();

	/**
	 * Sets the primary key of this completed.
	 *
	 * @param primaryKey the primary key of this completed
	 */
	public void setPrimaryKey(CompletedPK primaryKey);

	/**
	 * Returns the u s e r_ i d of this completed.
	 *
	 * @return the u s e r_ i d of this completed
	 */
	@AutoEscape
	public String getUSER_ID();

	/**
	 * Sets the u s e r_ i d of this completed.
	 *
	 * @param USER_ID the u s e r_ i d of this completed
	 */
	public void setUSER_ID(String USER_ID);

	/**
	 * Returns the l a y o u t_ p k of this completed.
	 *
	 * @return the l a y o u t_ p k of this completed
	 */
	@AutoEscape
	public String getLAYOUT_PK();

	/**
	 * Sets the l a y o u t_ p k of this completed.
	 *
	 * @param LAYOUT_PK the l a y o u t_ p k of this completed
	 */
	public void setLAYOUT_PK(String LAYOUT_PK);

	/**
	 * Returns the a r t i c l e s_ s e t_ i d of this completed.
	 *
	 * @return the a r t i c l e s_ s e t_ i d of this completed
	 */
	@AutoEscape
	public String getARTICLES_SET_ID();

	/**
	 * Sets the a r t i c l e s_ s e t_ i d of this completed.
	 *
	 * @param ARTICLES_SET_ID the a r t i c l e s_ s e t_ i d of this completed
	 */
	public void setARTICLES_SET_ID(String ARTICLES_SET_ID);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Completed completed);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Completed> toCacheModel();

	@Override
	public Completed toEscapedModel();

	@Override
	public Completed toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}