/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import com.rivetlogic.portlet.service.persistence.DriveLinksPK;

import java.io.Serializable;

/**
 * The base model interface for the DriveLinks service. Represents a row in the &quot;rivetlogic_DriveLinks&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rivetlogic.portlet.model.impl.DriveLinksModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rivetlogic.portlet.model.impl.DriveLinksImpl}.
 * </p>
 *
 * @author charlesrodriguez
 * @see DriveLinks
 * @see com.rivetlogic.portlet.model.impl.DriveLinksImpl
 * @see com.rivetlogic.portlet.model.impl.DriveLinksModelImpl
 * @generated
 */
public interface DriveLinksModel extends BaseModel<DriveLinks> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a drive links model instance should use the {@link DriveLinks} interface instead.
	 */

	/**
	 * Returns the primary key of this drive links.
	 *
	 * @return the primary key of this drive links
	 */
	public DriveLinksPK getPrimaryKey();

	/**
	 * Sets the primary key of this drive links.
	 *
	 * @param primaryKey the primary key of this drive links
	 */
	public void setPrimaryKey(DriveLinksPK primaryKey);

	/**
	 * Returns the u s e r_ i d of this drive links.
	 *
	 * @return the u s e r_ i d of this drive links
	 */
	@AutoEscape
	public String getUSER_ID();

	/**
	 * Sets the u s e r_ i d of this drive links.
	 *
	 * @param USER_ID the u s e r_ i d of this drive links
	 */
	public void setUSER_ID(String USER_ID);

	/**
	 * Returns the n a m e of this drive links.
	 *
	 * @return the n a m e of this drive links
	 */
	@AutoEscape
	public String getNAME();

	/**
	 * Sets the n a m e of this drive links.
	 *
	 * @param NAME the n a m e of this drive links
	 */
	public void setNAME(String NAME);

	/**
	 * Returns the u r l of this drive links.
	 *
	 * @return the u r l of this drive links
	 */
	@AutoEscape
	public String getURL();

	/**
	 * Sets the u r l of this drive links.
	 *
	 * @param URL the u r l of this drive links
	 */
	public void setURL(String URL);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DriveLinks driveLinks);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DriveLinks> toCacheModel();

	@Override
	public DriveLinks toEscapedModel();

	@Override
	public DriveLinks toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}